In [18]:
import numpy as np
import S4
import matplotlib.pyplot as plt
import time


#variables setting
grating_thickness = 325e-9
nG = 100
wl = 1250e-9
ang = 55
ncells = 64
period = abs(wl/np.sin(ang/180*np.pi))
freq = 3e8/wl
S = S4.New(Lattice=((period,0),(0,period/2)), NumBasis=nG)

# Permittivities & thickness[um]
eps_SiO2 = 1.4504**2
eps_Si = 3.5750**2   #shd be altered


#import & save the structure
gratingMatrix = np.load('struct.npy')
np.savetxt('gratingMatrix.csv',gratingMatrix,delimiter=",")

xnum = np.shape(gratingMatrix)[0]
ynum = np.shape(gratingMatrix)[1]
print('x: ', xnum, ' y: ', ynum)


start = time.time()

S.SetFrequency(freq)
S.SetMaterial(Name = 'SiO2', Epsilon = eps_SiO2)
S.SetMaterial(Name = 'Vacuum', Epsilon = 1)
S.SetMaterial(Name = 'Si', Epsilon = eps_Si)

#S.AddLayer(Name = 'toptop', Thickness = 0, Material= 'Vacuum')
S.AddLayer(Name = 'top', Thickness = 0, Material= 'SiO2')
S.AddLayer(Name = 'grating', Thickness = grating_thickness, Material = 'Vacuum')
S.AddLayer(Name = 'bottom', Thickness = 0, Material = 'Vacuum')

S.SetExcitationPlanewave(
        IncidenceAngles = (0,0),
        sAmplitude = 1,
        pAmplitude = 0
        )


S.SetOptions( # these are the defaults
    Verbosity = 1,
    LatticeTruncation = 'Circular',
    DiscretizedEpsilon = False,
    DiscretizationResolution = 8,
    PolarizationDecomposition = True,
    PolarizationBasis = 'Normal',
    LanczosSmoothing = False,
    SubpixelSmoothing = False,
    ConserveMemory = False
    )

for i1 in range(xnum):
    for i2 in range(ynum):
        if gratingMatrix[i1][i2]:
            S.SetRegionRectangle(
                        Layer='grating',
                        Material = 'Si',
                        #Center = ((i1-(howMany-1)/2)*period/howMany,(i2-(howMany-1)/2)*period/howMany),
                        Center = (-period/2+period/(2*xnum) + i1*(period/xnum), -period/4+period/(4*ynum) + i2*(period/ynum)),
                        Angle = 0,
                        Halfwidths = (period/(2*xnum), period/(4*ynum))
                        )
    
P_reflection = np.asarray(S.GetPowerFluxByOrder(Layer = 'top', zOffset = 0))
P_transmission = np.asarray(S.GetPowerFluxByOrder(Layer = 'bottom', zOffset = 0))
efficiency = np.real(P_transmission[1,0])*100
end = time.time()

timecost = end - start

print('time8')
print(timecost)
print('eff8')
print(efficiency)


x:  128  y:  256
time8
52.260446071624756
eff8
1.5986232555119457


In [20]:
xnum

128

In [19]:
P_transmission

array([[0.03493671+0.j, 0.        +0.j],
       [0.01598623+0.j, 0.        +0.j],
       [0.01154604+0.j, 0.        +0.j],
       [0.02376859+0.j, 0.        +0.j],
       [0.01566413+0.j, 0.        +0.j],
       [0.01711273+0.j, 0.        +0.j],
       [0.00994617+0.j, 0.        +0.j],
       [0.01821953+0.j, 0.        +0.j],
       [0.01627451+0.j, 0.        +0.j],
       [0.00219683+0.j, 0.        +0.j],
       [0.00865157+0.j, 0.        +0.j],
       [0.00129511+0.j, 0.        +0.j],
       [0.00389218+0.j, 0.        +0.j],
       [0.00181934+0.j, 0.        +0.j],
       [0.01856284+0.j, 0.        +0.j],
       [0.00702148+0.j, 0.        +0.j],
       [0.01520565+0.j, 0.        +0.j],
       [0.0032908 +0.j, 0.        +0.j],
       [0.00114558+0.j, 0.        +0.j],
       [0.01925134+0.j, 0.        +0.j],
       [0.00385691+0.j, 0.        +0.j],
       [0.01619233+0.j, 0.        +0.j],
       [0.02070319+0.j, 0.        +0.j],
       [0.00261669+0.j, 0.        +0.j],
       [0.013034

In [12]:
print (gratingMatrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
